BTN_MISION_1 = "templates/btn_mision_1_lt.png"
BTN_MISION_2 = "templates/btn_mision_2_lt.png"
BTN_MISION_3 = "templates/btn_mision_3_lt.png"
BTN_MISION_4 = "templates/btn_mision_4_lt.png"

BTN_STORY = "templates/btn_story_lt.png"
BTN_MISIONES = "templates/btn_misiones_lt.png"
BTN_JUGAR = "templates/btn_jugar_lt.png"
BTN_INICIAR = "templates/btn_iniciar_lt.png"
BTN_MANUAL = "templates/btn_manual_lt.png"
BTN_1X = "templates/btn_1x_lt.png"
BTN_RECLAMAR = "templates/btn_reclamar_lt.png"
BTN_CONTINUAR = "templates/btn_continuar_lt.png"
BTN_SALIR = "templates/btn_salir_lt.png"
BTN_EMBERS = "templates/btn_embers_lt.png"
BTN_JUGAR_EMBER = "templates/btn_jugar_ember_lt.png"
BTN_RETRY = "templates/btn_retry_lt.png"

BTN_EASY = ""
BTN_MEDIUM = ""
BTN_HARD = ""

BTN_FUEGO = "templates/btn_fuego_lt.png"
BTN_TIERRA = "templates/btn_tierra_lt.png"
BTN_AIRE = "templates/btn_aire_lt.png"
BTN_TRUENO = "templates/btn_trueno_lt.png"
BTN_PLANTA = "templates/btn_planta_lt.png"
BTN_AGUA = "templates/btn_agua_lt.png"
BTN_HIELO = "templates/btn_hielo_lt.png"

ENERGY_0 = "templates/energy_0.png"
ENERGY_1 = "templates/energy_1.png"
ENERGY_2 = "templates/energy_2.png"
ENERGY_3 = "templates/energy_3.png"
ENERGY_4 = "templates/energy_4.png"
ENERGY_5 = "templates/energy_5.png"
ENERGY_6 = "templates/energy_6.png"
ENERGY_7 = "templates/energy_7.png"
ENERGY_8 = "templates/energy_8.png"
ENERGY_9 = "templates/energy_9.png"

MAIN_SCREEN = "templates/main_screen_lt_2.png"
EMBER_SCREEN = "templates/ember_screen_lt.png"
MISIONS_SCREEN = "templates/misions_screen_lt_2.png"
STORY_SCREEN = "templates/story_screen_lt_2.png"